# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.fabric-iot.edu:
    container_name: orderer.fabric-iot.edu
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../../crypto-config/ordererOrganizations/fabric-iot.edu/orderers/orderer.fabric-iot.edu/msp:/var/hyperledger/orderer/msp
        - ../../crypto-config/ordererOrganizations/fabric-iot.edu/orderers/orderer.fabric-iot.edu/tls/:/var/hyperledger/orderer/tls
        - orderer.fabric-iot.edu:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.fabric-iot.edu:
    container_name: peer0.org1.fabric-iot.edu
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.fabric-iot.edu
      - CORE_PEER_ADDRESS=peer0.org1.fabric-iot.edu:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.fabric-iot.edu:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.fabric-iot.edu:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.fabric-iot.edu:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org1.fabric-iot.edu/peers/peer0.org1.fabric-iot.edu/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org1.fabric-iot.edu/peers/peer0.org1.fabric-iot.edu/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.fabric-iot.edu:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.fabric-iot.edu:
    container_name: peer1.org1.fabric-iot.edu
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.fabric-iot.edu
      - CORE_PEER_ADDRESS=peer1.org1.fabric-iot.edu:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.fabric-iot.edu:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.fabric-iot.edu:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.fabric-iot.edu:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org1.fabric-iot.edu/peers/peer1.org1.fabric-iot.edu/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org1.fabric-iot.edu/peers/peer1.org1.fabric-iot.edu/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.fabric-iot.edu:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.org2.fabric-iot.edu:
    container_name: peer0.org2.fabric-iot.edu
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.fabric-iot.edu
      - CORE_PEER_ADDRESS=peer0.org2.fabric-iot.edu:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.fabric-iot.edu:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.fabric-iot.edu:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.fabric-iot.edu:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org2.fabric-iot.edu/peers/peer0.org2.fabric-iot.edu/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org2.fabric-iot.edu/peers/peer0.org2.fabric-iot.edu/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.fabric-iot.edu:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.org2.fabric-iot.edu:
    container_name: peer1.org2.fabric-iot.edu
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.fabric-iot.edu
      - CORE_PEER_ADDRESS=peer1.org2.fabric-iot.edu:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.fabric-iot.edu:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.fabric-iot.edu:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.fabric-iot.edu:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org2.fabric-iot.edu/peers/peer1.org2.fabric-iot.edu/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org2.fabric-iot.edu/peers/peer1.org2.fabric-iot.edu/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.fabric-iot.edu:/var/hyperledger/production
    ports:
      - 10051:10051
