# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.fabric-iot.edu:
  peer0.org1.fabric-iot.edu:
  peer1.org1.fabric-iot.edu:
  peer0.org2.fabric-iot.edu:
  peer1.org2.fabric-iot.edu:

networks:
  bc_net:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.fabric-iot.edu-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.fabric-iot.edu-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./../crypto-config/peerOrganizations/org1.fabric-iot.edu/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - bc_net

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.fabric-iot.edu-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.fabric-iot.edu-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./../crypto-config/peerOrganizations/org2.fabric-iot.edu/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - bc_net

  orderer.fabric-iot.edu:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.fabric-iot.edu
    container_name: orderer.fabric-iot.edu
    networks:
      - bc_net

  peer0.org1.fabric-iot.edu:
    container_name: peer0.org1.fabric-iot.edu
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.fabric-iot.edu
    networks:
      - bc_net

  peer1.org1.fabric-iot.edu:
    container_name: peer1.org1.fabric-iot.edu
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.fabric-iot.edu
    networks:
      - bc_net

  peer0.org2.fabric-iot.edu:
    container_name: peer0.org2.fabric-iot.edu
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.fabric-iot.edu
    networks:
      - bc_net

  peer1.org2.fabric-iot.edu:
    container_name: peer1.org2.fabric-iot.edu
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.fabric-iot.edu
    networks:
      - bc_net
